CREATE TABLESPACE ProyectoBD2_Final
DATAFILE 'C:\APP\ANDRE\PRODUCT\21C\ORADATA\XE\XEPDB1\ProyectoBD2_Final.DBF'
SIZE 128M
AUTOEXTEND ON NEXT 64M MAXSIZE 2048M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE TempProyectoBD2_Final
TEMPFILE 'C:\APP\ANDRE\PRODUCT\21C\ORADATA\XE\XEPDB1\TempProyectoBD2_Final.DBF'
SIZE 128M

CREATE USER proyectoFinal_user IDENTIFIED BY proyectoFinal
DEFAULT TABLESPACE ProyectoBD2_Final
TEMPORARY TABLESPACE TempProyectoBD2_Final
QUOTA UNLIMITED ON ProyectoBD2_Final;

-- ------------------------------------------------------------------------------------------------------
-- --------------------------CREACION DE LAS TABLAS------------------------------------------------------

CREATE TABLE Tipo_donacion (
    tipo_donacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    calificacion_max NUMBER(3)
);

CREATE TABLE Organizacion (
    organizacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(255),
    telefono VARCHAR2(15),
    email VARCHAR2(100),
    estado VARCHAR2(20),
    fecha_registro DATE DEFAULT SYSDATE
);

CREATE TABLE Voluntario (
    voluntario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR2(15) UNIQUE NOT NULL,
    nombres VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    fecha_nacimiento DATE,
    email VARCHAR2(100),
    telefono VARCHAR2(15),
    direccion VARCHAR2(255),
    estado_civil VARCHAR2(30),
    fecha_registro DATE DEFAULT SYSDATE
);

CREATE TABLE Categoria (
    categoria_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    calificacion_max NUMBER(3)
);

CREATE TABLE Actividad (
    actividad_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id NUMBER NOT NULL,
    categoria_id NUMBER NOT NULL,
    nombre VARCHAR2(150) NOT NULL,
    descripcion VARCHAR2(255),
    ubicacion VARCHAR2(255),
    fecha_inicio DATE,
    fecha_fin DATE,
    estado VARCHAR2(20),
    CONSTRAINT fk_actividad_org FOREIGN KEY (organizacion_id)
        REFERENCES Organizacion (organizacion_id),
    CONSTRAINT fk_actividad_categoria FOREIGN KEY (categoria_id)
        REFERENCES Categoria (categoria_id)
);

CREATE TABLE Donacion (
    donacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voluntario_id NUMBER NOT NULL,
    organizacion_id NUMBER NOT NULL,
    tipo_donacion_id NUMBER NOT NULL,
    cantidad NUMBER(10,2),
    fecha DATE DEFAULT SYSDATE,
    calificacion NUMBER(3),
    CONSTRAINT fk_donacion_vol FOREIGN KEY (voluntario_id)
        REFERENCES Voluntario (voluntario_id),
    CONSTRAINT fk_donacion_org FOREIGN KEY (organizacion_id)
        REFERENCES Organizacion (organizacion_id),
    CONSTRAINT fk_donacion_tipo FOREIGN KEY (tipo_donacion_id)
        REFERENCES Tipo_donacion (tipo_donacion_id)
);

CREATE TABLE Asignacion_actividades (
    asignacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voluntario_id NUMBER NOT NULL,
    actividad_id NUMBER NOT NULL,
    fecha DATE DEFAULT SYSDATE,
    estado VARCHAR2(20),
    calificacion NUMBER(3),
    CONSTRAINT fk_asignacion_vol FOREIGN KEY (voluntario_id)
        REFERENCES Voluntario (voluntario_id),
    CONSTRAINT fk_asignacion_act FOREIGN KEY (actividad_id)
        REFERENCES Actividad (actividad_id)
);

select * from Categoria;

-- Sincronizar Contadores
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(tipo_donacion_id), 0) + 1 INTO v_max FROM Tipo_donacion;
    EXECUTE IMMEDIATE 'ALTER TABLE Tipo_donacion MODIFY tipo_donacion_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(organizacion_id), 0) + 1 INTO v_max FROM Organizacion;
    EXECUTE IMMEDIATE 'ALTER TABLE Organizacion MODIFY organizacion_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(voluntario_id), 0) + 1 INTO v_max FROM Voluntario;
    EXECUTE IMMEDIATE 'ALTER TABLE Voluntario MODIFY voluntario_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(categoria_id), 0) + 1 INTO v_max FROM Categoria;
    EXECUTE IMMEDIATE 'ALTER TABLE Categoria MODIFY categoria_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(actividad_id), 0) + 1 INTO v_max FROM Actividad;
    EXECUTE IMMEDIATE 'ALTER TABLE Actividad MODIFY actividad_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(donacion_id), 0) + 1 INTO v_max FROM Donacion;
    EXECUTE IMMEDIATE 'ALTER TABLE Donacion MODIFY donacion_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(asignacion_id), 0) + 1 INTO v_max FROM Asignacion_actividades;
    EXECUTE IMMEDIATE 'ALTER TABLE Asignacion_actividades MODIFY asignacion_id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;
/
-- ------------------------------------------------------------------------------------------------------
-- -------------Scripts de Creación de Objetos de Programación almacenados-------------------------------
--Procedimiento almacenado: Activar o desactivar organizacion

CREATE OR REPLACE PROCEDURE DesactivarOrganizacion (
    p_organizacion_id IN NUMBER
)
AS
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists 
    FROM Organizacion
    WHERE organizacion_id = p_organizacion_id;

    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'La organización no existe.');
    END IF;

    UPDATE Organizacion
    SET estado = 'INACTIVO'
    WHERE organizacion_id = p_organizacion_id;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Organización desactivada correctamente.');
END;
/

CREATE OR REPLACE PROCEDURE ActivarOrganizacion (
    p_organizacion_id IN NUMBER
)
AS
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists 
    FROM Organizacion
    WHERE organizacion_id = p_organizacion_id;

    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'La organización no existe.');
    END IF;

    UPDATE Organizacion
    SET estado = 'ACTIVA'
    WHERE organizacion_id = p_organizacion_id;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Organización activada correctamente.');
END;
/

-- Procedimiento: Registrar Tipo de Donación
CREATE OR REPLACE PROCEDURE RegistrarTipoDonacion (
    p_nombre           IN VARCHAR2,
    p_descripcion      IN VARCHAR2,
    p_calificacion_max IN NUMBER
)
AS
    v_exists NUMBER;
BEGIN
    -- Verificar que el nombre no esté duplicado
    SELECT COUNT(*) INTO v_exists 
    FROM Tipo_donacion 
    WHERE UPPER(nombre) = UPPER(p_nombre);
    
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20030, 'Ya existe un tipo de donación con este nombre.');
    END IF;
    
    -- Validar calificación máxima
    IF p_calificacion_max IS NOT NULL AND (p_calificacion_max < 0 OR p_calificacion_max > 100) THEN
        RAISE_APPLICATION_ERROR(-20031, 'La calificación máxima debe estar entre 0 y 100.');
    END IF;

    -- Insertar el tipo de donación
    INSERT INTO Tipo_donacion (
        nombre, descripcion, calificacion_max
    ) VALUES (
        p_nombre, p_descripcion, p_calificacion_max
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Tipo de donación registrado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END RegistrarTipoDonacion;
/

-- Procedimiento: Modificar Tipo de Donación
CREATE OR REPLACE PROCEDURE ModificarTipoDonacion (
    p_tipo_donacion_id IN NUMBER,
    p_nombre           IN VARCHAR2,
    p_descripcion      IN VARCHAR2,
    p_calificacion_max IN NUMBER
)
AS
    v_exists NUMBER;
BEGIN
    -- Verificar que el tipo de donación existe
    SELECT COUNT(*) INTO v_exists 
    FROM Tipo_donacion 
    WHERE tipo_donacion_id = p_tipo_donacion_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20032, 'El tipo de donación no existe.');
    END IF;

    -- Verificar que el nombre no esté duplicado (excepto el mismo registro)
    SELECT COUNT(*) INTO v_exists 
    FROM Tipo_donacion 
    WHERE UPPER(nombre) = UPPER(p_nombre)
    AND tipo_donacion_id != p_tipo_donacion_id;
    
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20030, 'Ya existe otro tipo de donación con este nombre.');
    END IF;
    
    -- Validar calificación máxima
    IF p_calificacion_max IS NOT NULL AND (p_calificacion_max < 0 OR p_calificacion_max > 100) THEN
        RAISE_APPLICATION_ERROR(-20031, 'La calificación máxima debe estar entre 0 y 100.');
    END IF;

    -- Actualizar el tipo de donación
    UPDATE Tipo_donacion
    SET nombre = p_nombre,
        descripcion = p_descripcion,
        calificacion_max = p_calificacion_max
    WHERE tipo_donacion_id = p_tipo_donacion_id;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Tipo de donación modificado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ModificarTipoDonacion;
/

-- Procedimiento: Registrar Categoría
CREATE OR REPLACE PROCEDURE RegistrarCategoria (
    p_nombre           IN VARCHAR2,
    p_descripcion      IN VARCHAR2,
    p_calificacion_max IN NUMBER
)
AS
    v_exists NUMBER;
BEGIN
    -- Verificar que el nombre no esté duplicado
    SELECT COUNT(*) INTO v_exists 
    FROM Categoria 
    WHERE UPPER(nombre) = UPPER(p_nombre);
    
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20020, 'Ya existe una categoría con este nombre.');
    END IF;
    
    -- Validar calificación máxima
    IF p_calificacion_max IS NOT NULL AND (p_calificacion_max < 0 OR p_calificacion_max > 100) THEN
        RAISE_APPLICATION_ERROR(-20021, 'La calificación máxima debe estar entre 0 y 100.');
    END IF;

    -- Insertar la categoría
    INSERT INTO Categoria (
        nombre, descripcion, calificacion_max
    ) VALUES (
        p_nombre, p_descripcion, p_calificacion_max
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Categoría registrada correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END RegistrarCategoria;
/

-- Procedimiento: Modificar Categoría
CREATE OR REPLACE PROCEDURE ModificarCategoria (
    p_categoria_id     IN NUMBER,
    p_nombre           IN VARCHAR2,
    p_descripcion      IN VARCHAR2,
    p_calificacion_max IN NUMBER
)
AS
    v_exists NUMBER;
BEGIN
    -- Verificar que la categoría existe
    SELECT COUNT(*) INTO v_exists 
    FROM Categoria 
    WHERE categoria_id = p_categoria_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20022, 'La categoría no existe.');
    END IF;

    -- Verificar que el nombre no esté duplicado (excepto el mismo registro)
    SELECT COUNT(*) INTO v_exists 
    FROM Categoria 
    WHERE UPPER(nombre) = UPPER(p_nombre)
    AND categoria_id != p_categoria_id;
    
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20020, 'Ya existe otra categoría con este nombre.');
    END IF;
    
    -- Validar calificación máxima
    IF p_calificacion_max IS NOT NULL AND (p_calificacion_max < 0 OR p_calificacion_max > 100) THEN
        RAISE_APPLICATION_ERROR(-20021, 'La calificación máxima debe estar entre 0 y 100.');
    END IF;

    -- Actualizar la categoría
    UPDATE Categoria
    SET nombre = p_nombre,
        descripcion = p_descripcion,
        calificacion_max = p_calificacion_max
    WHERE categoria_id = p_categoria_id;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Categoría modificada correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ModificarCategoria;
/

-- Procedimiento: Registrar Voluntario
CREATE OR REPLACE PROCEDURE RegistrarVoluntario (
    p_dni            IN VARCHAR2,
    p_nombres        IN VARCHAR2,
    p_apellidos      IN VARCHAR2,
    p_fecha_nac      IN DATE,
    p_email          IN VARCHAR2,
    p_telefono       IN VARCHAR2,
    p_direccion      IN VARCHAR2,
    p_estado_civil   IN VARCHAR2
)
AS
    v_exists NUMBER;
BEGIN
    -- Verificar que el DNI no esté duplicado
    SELECT COUNT(*) INTO v_exists 
    FROM Voluntario 
    WHERE dni = p_dni;
    
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 'Ya existe un voluntario con este DNI.');
    END IF;

    -- Verificar que el email no esté duplicado (si se proporciona)
    IF p_email IS NOT NULL THEN
        SELECT COUNT(*) INTO v_exists 
        FROM Voluntario 
        WHERE UPPER(email) = UPPER(p_email);
        
        IF v_exists > 0 THEN
            RAISE_APPLICATION_ERROR(-20011, 'Ya existe un voluntario con este email.');
        END IF;
    END IF;

    -- Insertar el voluntario
    INSERT INTO Voluntario (
        dni, nombres, apellidos, fecha_nacimiento,
        email, telefono, direccion, estado_civil, fecha_registro
    ) VALUES (
        p_dni, p_nombres, p_apellidos, p_fecha_nac,
        p_email, p_telefono, p_direccion, p_estado_civil, SYSDATE
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Voluntario registrado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END RegistrarVoluntario;
/

-- Procedimiento: Modificar Voluntario
CREATE OR REPLACE PROCEDURE ModificarVoluntario (
    p_voluntario_id  IN NUMBER,
    p_dni            IN VARCHAR2,
    p_nombres        IN VARCHAR2,
    p_apellidos      IN VARCHAR2,
    p_fecha_nac      IN DATE,
    p_email          IN VARCHAR2,
    p_telefono       IN VARCHAR2,
    p_direccion      IN VARCHAR2,
    p_estado_civil   IN VARCHAR2
)
AS
    v_exists NUMBER;
BEGIN
    -- Verificar que el voluntario existe
    SELECT COUNT(*) INTO v_exists 
    FROM Voluntario 
    WHERE voluntario_id = p_voluntario_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20012, 'El voluntario no existe.');
    END IF;

    -- Verificar que el DNI no esté duplicado (excepto el mismo registro)
    SELECT COUNT(*) INTO v_exists 
    FROM Voluntario 
    WHERE dni = p_dni
    AND voluntario_id != p_voluntario_id;
    
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 'Ya existe otro voluntario con este DNI.');
    END IF;

    -- Verificar que el email no esté duplicado (excepto el mismo registro)
    IF p_email IS NOT NULL THEN
        SELECT COUNT(*) INTO v_exists 
        FROM Voluntario 
        WHERE UPPER(email) = UPPER(p_email)
        AND voluntario_id != p_voluntario_id;
        
        IF v_exists > 0 THEN
            RAISE_APPLICATION_ERROR(-20011, 'Ya existe otro voluntario con este email.');
        END IF;
    END IF;

    -- Actualizar el voluntario
    UPDATE Voluntario
    SET dni = p_dni,
        nombres = p_nombres,
        apellidos = p_apellidos,
        fecha_nacimiento = p_fecha_nac,
        email = p_email,
        telefono = p_telefono,
        direccion = p_direccion,
        estado_civil = p_estado_civil
    WHERE voluntario_id = p_voluntario_id;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Voluntario modificado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ModificarVoluntario;
/

-- Procedimiento: Registrar Actividad
CREATE OR REPLACE PROCEDURE RegistrarActividad (
    p_organizacion_id IN NUMBER,
    p_categoria_id    IN NUMBER,
    p_nombre          IN VARCHAR2,
    p_descripcion     IN VARCHAR2,
    p_ubicacion       IN VARCHAR2,
    p_fecha_inicio    IN DATE,
    p_fecha_fin       IN DATE
)
AS
    v_exists NUMBER;
    v_estado VARCHAR2(20);
BEGIN
    -- Verificar que la organización existe
    SELECT COUNT(*) INTO v_exists 
    FROM Organizacion 
    WHERE organizacion_id = p_organizacion_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20040, 'La organización no existe.');
    END IF;
    
    -- Verificar que la categoría existe
    SELECT COUNT(*) INTO v_exists 
    FROM Categoria 
    WHERE categoria_id = p_categoria_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20041, 'La categoría no existe.');
    END IF;
    
    -- Validar fechas
    IF p_fecha_fin IS NOT NULL AND p_fecha_inicio > p_fecha_fin THEN
        RAISE_APPLICATION_ERROR(-20042, 'La fecha de inicio no puede ser posterior a la fecha de fin.');
    END IF;
    
    -- Determinar el estado según las fechas
    IF p_fecha_inicio > SYSDATE THEN
        v_estado := 'Programada';
    ELSIF p_fecha_inicio <= SYSDATE AND (p_fecha_fin IS NULL OR p_fecha_fin > SYSDATE) THEN
        v_estado := 'En curso';
    ELSE
        v_estado := 'Finalizada';
    END IF;
    
    -- Insertar la actividad
    INSERT INTO Actividad (
        organizacion_id, categoria_id, nombre, descripcion, 
        ubicacion, fecha_inicio, fecha_fin, estado
    ) VALUES (
        p_organizacion_id, p_categoria_id, p_nombre, p_descripcion,
        p_ubicacion, p_fecha_inicio, p_fecha_fin, v_estado
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Actividad registrada correctamente con estado: ' || v_estado);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END RegistrarActividad;
/

-- Procedimiento: Modificar Actividad
CREATE OR REPLACE PROCEDURE ModificarActividad (
    p_actividad_id    IN NUMBER,
    p_organizacion_id IN NUMBER,
    p_categoria_id    IN NUMBER,
    p_nombre          IN VARCHAR2,
    p_descripcion     IN VARCHAR2,
    p_ubicacion       IN VARCHAR2,
    p_fecha_inicio    IN DATE,
    p_fecha_fin       IN DATE
)
AS
    v_exists NUMBER;
    v_estado VARCHAR2(20);
BEGIN
    -- Verificar que la actividad existe
    SELECT COUNT(*) INTO v_exists 
    FROM Actividad 
    WHERE actividad_id = p_actividad_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20043, 'La actividad no existe.');
    END IF;
    
    -- Verificar que la organización existe
    SELECT COUNT(*) INTO v_exists 
    FROM Organizacion 
    WHERE organizacion_id = p_organizacion_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20040, 'La organización no existe.');
    END IF;
    
    -- Verificar que la categoría existe
    SELECT COUNT(*) INTO v_exists 
    FROM Categoria 
    WHERE categoria_id = p_categoria_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20041, 'La categoría no existe.');
    END IF;
    
    -- Validar fechas
    IF p_fecha_fin IS NOT NULL AND p_fecha_inicio > p_fecha_fin THEN
        RAISE_APPLICATION_ERROR(-20042, 'La fecha de inicio no puede ser posterior a la fecha de fin.');
    END IF;
    
    -- Determinar el estado según las fechas
    IF p_fecha_inicio > SYSDATE THEN
        v_estado := 'Programada';
    ELSIF p_fecha_inicio <= SYSDATE AND (p_fecha_fin IS NULL OR p_fecha_fin > SYSDATE) THEN
        v_estado := 'En curso';
    ELSE
        v_estado := 'Finalizada';
    END IF;
    
    -- Actualizar la actividad
    UPDATE Actividad
    SET organizacion_id = p_organizacion_id,
        categoria_id = p_categoria_id,
        nombre = p_nombre,
        descripcion = p_descripcion,
        ubicacion = p_ubicacion,
        fecha_inicio = p_fecha_inicio,
        fecha_fin = p_fecha_fin,
        estado = v_estado
    WHERE actividad_id = p_actividad_id;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Actividad modificada correctamente con estado: ' || v_estado);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ModificarActividad;
/

-- ========== PROCEDIMIENTO ALMACENADO: Modificar organización ==========
CREATE OR REPLACE PROCEDURE ModificarOrganizacion (
    p_organizacion_id IN NUMBER,
    p_nombre          IN VARCHAR2,
    p_direccion       IN VARCHAR2,
    p_telefono        IN VARCHAR2,
    p_email           IN VARCHAR2
)
AS
    v_exists NUMBER;
    v_email_exists NUMBER;
    v_nombre_exists NUMBER;
BEGIN
    -- Verificar que la organización existe
    SELECT COUNT(*) INTO v_exists 
    FROM Organizacion 
    WHERE organizacion_id = p_organizacion_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20005, 'La organización no existe.');
    END IF;

    -- Verificar que el email no esté duplicado (excepto el mismo registro)
    SELECT COUNT(*) INTO v_email_exists 
    FROM Organizacion 
    WHERE UPPER(email) = UPPER(p_email)
    AND organizacion_id != p_organizacion_id;
    
    IF v_email_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Ya existe otra organización con este email.');
    END IF;

    -- Verificar que el nombre no esté duplicado (excepto el mismo registro)
    SELECT COUNT(*) INTO v_nombre_exists 
    FROM Organizacion 
    WHERE UPPER(nombre) = UPPER(p_nombre)
    AND organizacion_id != p_organizacion_id;
    
    IF v_nombre_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Ya existe otra organización con este nombre.');
    END IF;

    -- Actualizar la organización
    UPDATE Organizacion
    SET nombre = p_nombre,
        direccion = p_direccion,
        telefono = p_telefono,
        email = p_email
    WHERE organizacion_id = p_organizacion_id;

    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Organización modificada correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ModificarOrganizacion;
/

-- ========== PROCEDIMIENTO ALMACENADO: Registrar nueva organización ==========
-- Agrega este código a tu script SQL de Oracle

CREATE OR REPLACE PROCEDURE RegistrarOrganizacion (
    p_nombre     IN VARCHAR2,
    p_direccion  IN VARCHAR2,
    p_telefono   IN VARCHAR2,
    p_email      IN VARCHAR2
)
AS
    v_exists NUMBER;
BEGIN
    -- Verificar que el email no esté duplicado
    SELECT COUNT(*) INTO v_exists 
    FROM Organizacion 
    WHERE UPPER(email) = UPPER(p_email);
    
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Ya existe una organización con este email.');
    END IF;

    -- Verificar que el nombre no esté duplicado
    SELECT COUNT(*) INTO v_exists 
    FROM Organizacion 
    WHERE UPPER(nombre) = UPPER(p_nombre);
    
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Ya existe una organización con este nombre.');
    END IF;

    -- Insertar la nueva organización
    INSERT INTO Organizacion (
        nombre,
        direccion,
        telefono,
        email,
        estado,
        fecha_registro
    ) VALUES (
        p_nombre,
        p_direccion,
        p_telefono,
        p_email,
        'ACTIVA',
        SYSDATE
    );

    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Organización registrada correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Procedimiento: Registrar Donación
CREATE OR REPLACE PROCEDURE RegistrarDonacion (
    p_voluntario_id     IN NUMBER,
    p_organizacion_id   IN NUMBER,
    p_tipo_donacion_id  IN NUMBER,
    p_cantidad          IN NUMBER,
    p_calificacion      IN NUMBER
)
AS
    v_exists NUMBER;
    v_cal_max NUMBER;
BEGIN
    -- Verificar que el voluntario existe
    SELECT COUNT(*) INTO v_exists 
    FROM Voluntario 
    WHERE voluntario_id = p_voluntario_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20050, 'El voluntario no existe.');
    END IF;
    
    -- Verificar que la organización existe y está activa
    SELECT COUNT(*) INTO v_exists 
    FROM Organizacion 
    WHERE organizacion_id = p_organizacion_id
    AND UPPER(estado) = 'ACTIVA';
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20051, 'La organización no existe o no está activa.');
    END IF;
    
    -- Verificar que el tipo de donación existe
    SELECT COUNT(*) INTO v_exists 
    FROM Tipo_donacion 
    WHERE tipo_donacion_id = p_tipo_donacion_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20052, 'El tipo de donación no existe.');
    END IF;
    
    -- Validar cantidad
    IF p_cantidad IS NOT NULL AND p_cantidad <= 0 THEN
        RAISE_APPLICATION_ERROR(-20053, 'La cantidad debe ser mayor a cero.');
    END IF;
    
    -- Validar calificación según el máximo del tipo de donación
    IF p_calificacion IS NOT NULL THEN
        SELECT calificacion_max INTO v_cal_max 
        FROM Tipo_donacion 
        WHERE tipo_donacion_id = p_tipo_donacion_id;
        
        IF v_cal_max IS NOT NULL AND (p_calificacion < 0 OR p_calificacion > v_cal_max) THEN
            RAISE_APPLICATION_ERROR(-20054, 
                'La calificación debe estar entre 0 y ' || v_cal_max || '.');
        END IF;
    END IF;
    
    -- Insertar la donación
    INSERT INTO Donacion (
        voluntario_id, organizacion_id, tipo_donacion_id,
        cantidad, fecha, calificacion
    ) VALUES (
        p_voluntario_id, p_organizacion_id, p_tipo_donacion_id,
        p_cantidad, SYSDATE, p_calificacion
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Donación registrada correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END RegistrarDonacion;
/

-- Procedimiento: Modificar Donación
CREATE OR REPLACE PROCEDURE ModificarDonacion (
    p_donacion_id       IN NUMBER,
    p_voluntario_id     IN NUMBER,
    p_organizacion_id   IN NUMBER,
    p_tipo_donacion_id  IN NUMBER,
    p_cantidad          IN NUMBER,
    p_calificacion      IN NUMBER
)
AS
    v_exists NUMBER;
    v_cal_max NUMBER;
BEGIN
    -- Verificar que la donación existe
    SELECT COUNT(*) INTO v_exists 
    FROM Donacion 
    WHERE donacion_id = p_donacion_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20055, 'La donación no existe.');
    END IF;
    
    -- Verificar que el voluntario existe
    SELECT COUNT(*) INTO v_exists 
    FROM Voluntario 
    WHERE voluntario_id = p_voluntario_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20050, 'El voluntario no existe.');
    END IF;
    
    -- Verificar que la organización existe y está activa
    SELECT COUNT(*) INTO v_exists 
    FROM Organizacion 
    WHERE organizacion_id = p_organizacion_id
    AND UPPER(estado) = 'ACTIVA';
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20051, 'La organización no existe o no está activa.');
    END IF;
    
    -- Verificar que el tipo de donación existe
    SELECT COUNT(*) INTO v_exists 
    FROM Tipo_donacion 
    WHERE tipo_donacion_id = p_tipo_donacion_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20052, 'El tipo de donación no existe.');
    END IF;
    
    -- Validar cantidad
    IF p_cantidad IS NOT NULL AND p_cantidad <= 0 THEN
        RAISE_APPLICATION_ERROR(-20053, 'La cantidad debe ser mayor a cero.');
    END IF;
    
    -- Validar calificación según el máximo del tipo de donación
    IF p_calificacion IS NOT NULL THEN
        SELECT calificacion_max INTO v_cal_max 
        FROM Tipo_donacion 
        WHERE tipo_donacion_id = p_tipo_donacion_id;
        
        IF v_cal_max IS NOT NULL AND (p_calificacion < 0 OR p_calificacion > v_cal_max) THEN
            RAISE_APPLICATION_ERROR(-20054, 
                'La calificación debe estar entre 0 y ' || v_cal_max || '.');
        END IF;
    END IF;
    
    -- Actualizar la donación
    UPDATE Donacion
    SET voluntario_id = p_voluntario_id,
        organizacion_id = p_organizacion_id,
        tipo_donacion_id = p_tipo_donacion_id,
        cantidad = p_cantidad,
        calificacion = p_calificacion
    WHERE donacion_id = p_donacion_id;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Donación modificada correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ModificarDonacion;
/

--Procedimiento almacenado: Registrar nueva donación
--Automatiza el proceso de insertar donaciones nuevas, asegurando que solo se necesiten los parámetros principales (el sistema añade fecha y otros datos automáticamente)
CREATE OR REPLACE PROCEDURE RegistrarDonacion (
    p_voluntario_id     IN NUMBER,
    p_organizacion_id   IN NUMBER,
    p_tipo_donacion_id  IN NUMBER,
    p_cantidad          IN NUMBER,
    p_calificacion      IN NUMBER DEFAULT NULL
)
AS
    v_exists NUMBER;
BEGIN
    -- Verificar existencia del voluntario
    SELECT COUNT(*) INTO v_exists FROM Voluntario WHERE voluntario_id = p_voluntario_id;
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El voluntario no existe.');
    END IF;

    -- Verificar existencia de la organización
    SELECT COUNT(*) INTO v_exists FROM Organizacion WHERE organizacion_id = p_organizacion_id;
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'La organización no existe.');
    END IF;

    -- Verificar existencia del tipo de donación
    SELECT COUNT(*) INTO v_exists FROM Tipo_donacion WHERE tipo_donacion_id = p_tipo_donacion_id;
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'El tipo de donación no existe.');
    END IF;

    -- Inserción de la donación
    INSERT INTO Donacion (
        voluntario_id,
        organizacion_id,
        tipo_donacion_id,
        cantidad,
        fecha,
        calificacion
    ) VALUES (
        p_voluntario_id,
        p_organizacion_id,
        p_tipo_donacion_id,
        p_cantidad,
        SYSDATE,      
        p_calificacion
    );

    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Donación registrada correctamente.');
END;
/

SET SERVEROUTPUT ON;

BEGIN
    RegistrarDonacion( p_voluntario_id => 1, p_organizacion_id => 1, p_tipo_donacion_id => 1, p_cantidad => 250.75, p_calificacion => 95);
END;
/

--Función almacenada: Calcular total donado por voluntario
--Devuelve el monto total donado por un voluntario. Puede usarse en reportes o consultas de desempeño de voluntarios
CREATE OR REPLACE FUNCTION CalcularTotalDonado (
    p_voluntario_id IN NUMBER
) RETURN NUMBER
IS
    v_total NUMBER := 0;
BEGIN
    -- Calcula la suma total de donaciones realizadas por el voluntario
    SELECT NVL(SUM(cantidad), 0)
    INTO v_total
    FROM Donacion
    WHERE voluntario_id = p_voluntario_id;

    RETURN v_total;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

SELECT 
    v.voluntario_id,
    v.nombres,
    v.apellidos,
    CalcularTotalDonado(v.voluntario_id) AS total_donado
FROM Voluntario v;

-- Procedimiento que actualiza TODAS las actividades
CREATE OR REPLACE PROCEDURE ActualizarEstadosActividades AS
BEGIN
    UPDATE Actividad
    SET estado =
        CASE
            WHEN fecha_inicio > SYSDATE THEN 'Programada'
            WHEN fecha_fin <= SYSDATE THEN 'Finalizada'
            ELSE 'En curso'
        END;
    COMMIT;
END;
/

BEGIN
    ActualizarEstadosActividades;
END;
/

-- Procedimiento: Registrar Asignación
CREATE OR REPLACE PROCEDURE RegistrarAsignacion (
    p_voluntario_id  IN NUMBER,
    p_actividad_id   IN NUMBER,
    p_calificacion   IN NUMBER
)
AS
    v_exists NUMBER;
    v_cal_max NUMBER;
    v_estado VARCHAR2(20);
BEGIN
    -- Verificar que el voluntario existe
    SELECT COUNT(*) INTO v_exists 
    FROM Voluntario 
    WHERE voluntario_id = p_voluntario_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20060, 'El voluntario no existe.');
    END IF;
    
    -- Verificar que la actividad existe
    SELECT COUNT(*) INTO v_exists 
    FROM Actividad 
    WHERE actividad_id = p_actividad_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20061, 'La actividad no existe.');
    END IF;
    
    -- Verificar que no exista ya una asignación del mismo voluntario a la misma actividad
    SELECT COUNT(*) INTO v_exists 
    FROM Asignacion_actividades 
    WHERE voluntario_id = p_voluntario_id 
    AND actividad_id = p_actividad_id;
    
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20062, 'El voluntario ya está asignado a esta actividad.');
    END IF;
    
    -- Obtener calificación máxima de la categoría de la actividad
    SELECT c.calificacion_max INTO v_cal_max
    FROM Actividad a
    JOIN Categoria c ON a.categoria_id = c.categoria_id
    WHERE a.actividad_id = p_actividad_id;
    
    -- Validar calificación
    IF p_calificacion IS NOT NULL THEN
        IF v_cal_max IS NOT NULL AND (p_calificacion < 0 OR p_calificacion > v_cal_max) THEN
            RAISE_APPLICATION_ERROR(-20063, 
                'La calificación debe estar entre 0 y ' || v_cal_max || '.');
        END IF;
    END IF;
    
    -- Estado por defecto: Pendiente
    v_estado := 'Pendiente';
    
    -- Insertar la asignación
    INSERT INTO Asignacion_actividades (
        voluntario_id, actividad_id, fecha, estado, calificacion
    ) VALUES (
        p_voluntario_id, p_actividad_id, SYSDATE, v_estado, p_calificacion
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Asignación registrada correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END RegistrarAsignacion;
/

-- Procedimiento: Modificar Asignación
CREATE OR REPLACE PROCEDURE ModificarAsignacion (
    p_asignacion_id  IN NUMBER,
    p_voluntario_id  IN NUMBER,
    p_actividad_id   IN NUMBER,
    p_estado         IN VARCHAR2,
    p_calificacion   IN NUMBER
)
AS
    v_exists NUMBER;
    v_cal_max NUMBER;
BEGIN
    -- Verificar que la asignación existe
    SELECT COUNT(*) INTO v_exists 
    FROM Asignacion_actividades 
    WHERE asignacion_id = p_asignacion_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20064, 'La asignación no existe.');
    END IF;
    
    -- Verificar que el voluntario existe
    SELECT COUNT(*) INTO v_exists 
    FROM Voluntario 
    WHERE voluntario_id = p_voluntario_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20060, 'El voluntario no existe.');
    END IF;
    
    -- Verificar que la actividad existe
    SELECT COUNT(*) INTO v_exists 
    FROM Actividad 
    WHERE actividad_id = p_actividad_id;
    
    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20061, 'La actividad no existe.');
    END IF;
    
    -- Verificar duplicados (excepto la misma asignación)
    SELECT COUNT(*) INTO v_exists 
    FROM Asignacion_actividades 
    WHERE voluntario_id = p_voluntario_id 
    AND actividad_id = p_actividad_id
    AND asignacion_id != p_asignacion_id;
    
    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20062, 'El voluntario ya está asignado a esta actividad.');
    END IF;
    
    -- Obtener calificación máxima
    SELECT c.calificacion_max INTO v_cal_max
    FROM Actividad a
    JOIN Categoria c ON a.categoria_id = c.categoria_id
    WHERE a.actividad_id = p_actividad_id;
    
    -- Validar calificación
    IF p_calificacion IS NOT NULL THEN
        IF v_cal_max IS NOT NULL AND (p_calificacion < 0 OR p_calificacion > v_cal_max) THEN
            RAISE_APPLICATION_ERROR(-20063, 
                'La calificación debe estar entre 0 y ' || v_cal_max || '.');
        END IF;
    END IF;
    
    -- Actualizar la asignación
    UPDATE Asignacion_actividades
    SET voluntario_id = p_voluntario_id,
        actividad_id = p_actividad_id,
        estado = p_estado,
        calificacion = p_calificacion
    WHERE asignacion_id = p_asignacion_id;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Asignación modificada correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ModificarAsignacion;
/


-- Trigger: Actualizar estado de actividad automáticamente
--Actualiza automáticamente el estado de una actividad según sus fechas, evitando errores humanos y manteniendo la consistencia de datos
CREATE OR REPLACE TRIGGER ActualizarEstadoActividad
BEFORE INSERT OR UPDATE ON Actividad
FOR EACH ROW
BEGIN
    IF :NEW.fecha_inicio > SYSDATE THEN
        :NEW.estado := 'Programada';
    ELSIF :NEW.fecha_inicio <= SYSDATE 
       AND (:NEW.fecha_fin IS NULL OR :NEW.fecha_fin > SYSDATE) THEN
        :NEW.estado := 'En curso';
    ELSIF :NEW.fecha_fin <= SYSDATE THEN
        :NEW.estado := 'Finalizada';
    END IF;
END;
/

INSERT INTO Actividad (organizacion_id, categoria_id, nombre, descripcion, ubicacion, fecha_inicio, fecha_fin)
VALUES (1, 1, 'Campaña Escolar', 'Reparto de útiles escolares', 'Cuzco',
        TO_DATE('2025-12-01', 'YYYY-MM-DD'),
        TO_DATE('2025-12-05', 'YYYY-MM-DD'));
INSERT INTO Actividad (organizacion_id, categoria_id, nombre, descripcion, ubicacion, fecha_inicio, fecha_fin)
VALUES (1, 1, 'Donación de Sangre', 'Campaña en hospitales locales', 'Lima',
        SYSDATE - 1,
        SYSDATE + 2);
INSERT INTO Actividad (organizacion_id, categoria_id, nombre, descripcion, ubicacion, fecha_inicio, fecha_fin)
VALUES (1, 1, 'Reforestación 2023', 'Evento ecológico anual', 'Arequipa',
        TO_DATE('2023-01-10', 'YYYY-MM-DD'),
        TO_DATE('2023-01-12', 'YYYY-MM-DD'));
        
select * from Actividad;



-- Vista: Vista de donaciones detalladas
--Facilita las consultas y reportes mostrando toda la información de donaciones en una sola vista sin tener que hacer múltiples joins cada vez

CREATE OR REPLACE VIEW Donaciones_Detalladas AS
SELECT
    d.donacion_id,
    d.fecha AS fecha_donacion,
    d.cantidad,
    d.calificacion AS calificacion_donacion,
    
    v.voluntario_id,
    v.nombres || ' ' || v.apellidos AS nombre_voluntario,
    v.dni,
    v.email AS email_voluntario,
    
    o.organizacion_id,
    o.nombre AS nombre_organizacion,
    o.email AS email_organizacion,
    
    td.tipo_donacion_id,
    td.nombre AS tipo_donacion,
    td.descripcion AS descripcion_tipo_donacion
FROM Donacion d
JOIN Voluntario v ON d.voluntario_id = v.voluntario_id
JOIN Organizacion o ON d.organizacion_id = o.organizacion_id
JOIN Tipo_donacion td ON d.tipo_donacion_id = td.tipo_donacion_id;

SELECT *
FROM Donaciones_Detalladas
WHERE cantidad > 100
ORDER BY fecha_donacion DESC;

-- ========== VISTA PARA LISTAR ACTIVIDADES ==========

CREATE OR REPLACE VIEW Vista_Actividades AS
SELECT 
    a.actividad_id AS ID,
    o.nombre AS nombre_organizacion,
    c.nombre AS nombre_categoria,
    a.nombre AS nombre_actividad,
    a.descripcion,
    a.ubicacion,
    a.fecha_inicio,
    a.fecha_fin,
    a.estado,
    a.organizacion_id,
    a.categoria_id
FROM Actividad a
JOIN Organizacion o ON a.organizacion_id = o.organizacion_id
JOIN Categoria c ON a.categoria_id = c.categoria_id
ORDER BY a.fecha_inicio DESC;

--Vista para Organizaciones ACTIVAS
CREATE OR REPLACE VIEW Organizaciones_Activas AS
SELECT 
    organizacion_id,
    nombre,
    direccion,
    telefono,
    email,
    fecha_registro
FROM Organizacion
WHERE UPPER(estado) = 'ACTIVO';

--Vista para Organizaciones INACTIVAS
CREATE OR REPLACE VIEW Organizaciones_Inactivas AS
SELECT 
    organizacion_id,
    nombre,
    direccion,
    telefono,
    email,
    fecha_registro
FROM Organizacion
WHERE UPPER(estado) = 'INACTIVO';

-- ========== VISTA PARA LISTAR ASIGNACIONES ==========

CREATE OR REPLACE VIEW Vista_Asignaciones AS
SELECT 
    aa.asignacion_id AS ID,
    v.nombres || ' ' || v.apellidos AS nombre_voluntario,
    a.nombre AS nombre_actividad,
    aa.fecha,
    aa.estado,
    aa.calificacion,
    aa.voluntario_id,
    aa.actividad_id,
    c.calificacion_max
FROM Asignacion_actividades aa
JOIN Voluntario v ON aa.voluntario_id = v.voluntario_id
JOIN Actividad a ON aa.actividad_id = a.actividad_id
JOIN Categoria c ON a.categoria_id = c.categoria_id
ORDER BY aa.fecha DESC;

-- Verificar
SELECT * FROM Vista_Asignaciones;

-- ========== VISTA PARA LISTAR DONACIONES ==========

CREATE OR REPLACE VIEW Vista_Donaciones AS
SELECT 
    d.donacion_id AS ID,
    v.nombres || ' ' || v.apellidos AS nombre_voluntario,
    o.nombre AS nombre_organizacion,
    td.nombre AS tipo_donacion,
    d.cantidad,
    d.fecha,
    d.calificacion,
    d.voluntario_id,
    d.organizacion_id,
    d.tipo_donacion_id
FROM Donacion d
JOIN Voluntario v ON d.voluntario_id = v.voluntario_id
JOIN Organizacion o ON d.organizacion_id = o.organizacion_id
JOIN Tipo_donacion td ON d.tipo_donacion_id = td.tipo_donacion_id
ORDER BY d.fecha DESC;



--Paquete PL/SQL: Gestión de voluntarios
--Agrupa operaciones comunes relacionadas con voluntarios (registro y conteo), haciendo más organizada y reutilizable la lógica del sistema
CREATE OR REPLACE PACKAGE Voluntarios_Pkg
AS
    PROCEDURE RegistrarVoluntario(
        p_dni          IN VARCHAR2,
        p_nombres      IN VARCHAR2,
        p_apellidos    IN VARCHAR2,
        p_fecha_nac    IN DATE DEFAULT NULL,
        p_email        IN VARCHAR2 DEFAULT NULL,
        p_telefono     IN VARCHAR2 DEFAULT NULL,
        p_direccion    IN VARCHAR2 DEFAULT NULL,
        p_estado_civil IN VARCHAR2 DEFAULT NULL
    );
    FUNCTION ContarVoluntarios RETURN NUMBER;
END Voluntarios_Pkg;
/
CREATE OR REPLACE PACKAGE BODY Voluntarios_Pkg
AS
    PROCEDURE RegistrarVoluntario(
        p_dni          IN VARCHAR2,
        p_nombres      IN VARCHAR2,
        p_apellidos    IN VARCHAR2,
        p_fecha_nac    IN DATE DEFAULT NULL,
        p_email        IN VARCHAR2 DEFAULT NULL,
        p_telefono     IN VARCHAR2 DEFAULT NULL,
        p_direccion    IN VARCHAR2 DEFAULT NULL,
        p_estado_civil IN VARCHAR2 DEFAULT NULL
    )
    IS
    BEGIN
        INSERT INTO Voluntario (
            dni, nombres, apellidos, fecha_nacimiento,
            email, telefono, direccion, estado_civil, fecha_registro
        )
        VALUES (
            p_dni, p_nombres, p_apellidos, p_fecha_nac,
            p_email, p_telefono, p_direccion, p_estado_civil, SYSDATE
        );
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Voluntario registrado correctamente.');
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE('Error al registrar voluntario: ' || SQLERRM);
    END RegistrarVoluntario;
    FUNCTION ContarVoluntarios RETURN NUMBER
    IS
        v_total NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_total FROM Voluntario;
        RETURN v_total;
    END ContarVoluntarios;
END Voluntarios_Pkg;
/



