--------------------------------------------------------------------------------
-- SISTEMA DE VOLUNTARIADO INTEGRADO (SVI) - SCRIPT MAESTRO
-- Base de Datos: Oracle 21c XE
-- Fecha: Diciembre 2025
--------------------------------------------------------------------------------

-- =============================================================================
-- 1. CONFIGURACIÓN INICIAL (TABLESPACES Y USUARIO)
-- =============================================================================

CREATE TABLESPACE ProyectoBD2_Final
DATAFILE 'C:\APP\ANDRE\PRODUCT\21C\ORADATA\XE\XEPDB1\ProyectoBD2_Final.DBF'
SIZE 128M AUTOEXTEND ON NEXT 64M MAXSIZE 2048M
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE TempProyectoBD2_Final
TEMPFILE 'C:\APP\ANDRE\PRODUCT\21C\ORADATA\XE\XEPDB1\TempProyectoBD2_Final.DBF'
SIZE 128M;

CREATE USER proyectoFinal_user IDENTIFIED BY proyectoFinal
DEFAULT TABLESPACE ProyectoBD2_Final
TEMPORARY TABLESPACE TempProyectoBD2_Final
QUOTA UNLIMITED ON ProyectoBD2_Final;

GRANT CONNECT, RESOURCE, DBA TO proyectoFinal_user;

-- Conectarse como proyectoFinal_user antes de continuar...

-- =============================================================================
-- 2. LIMPIEZA DE OBJETOS PREVIOS (Para evitar errores de re-creación)
-- =============================================================================
BEGIN
    FOR i IN (SELECT object_name, object_type FROM user_objects WHERE object_type IN ('TABLE', 'VIEW', 'PACKAGE', 'PROCEDURE', 'FUNCTION', 'SEQUENCE')) LOOP
        BEGIN
            IF i.object_type = 'TABLE' THEN
                EXECUTE IMMEDIATE 'DROP TABLE ' || i.object_name || ' CASCADE CONSTRAINTS';
            ELSIF i.object_type = 'VIEW' THEN
                EXECUTE IMMEDIATE 'DROP VIEW ' || i.object_name;
            ELSIF i.object_type = 'PACKAGE' THEN
                EXECUTE IMMEDIATE 'DROP PACKAGE ' || i.object_name;
            ELSIF i.object_type = 'PROCEDURE' THEN
                EXECUTE IMMEDIATE 'DROP PROCEDURE ' || i.object_name;
            ELSIF i.object_type = 'FUNCTION' THEN
                EXECUTE IMMEDIATE 'DROP FUNCTION ' || i.object_name;
            END IF;
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

-- =============================================================================
-- 3. CREACIÓN DE TABLAS (Estructura Original)
-- =============================================================================

CREATE TABLE Tipo_donacion (
    tipo_donacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    calificacion_max NUMBER(3)
);

CREATE TABLE Organizacion (
    organizacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(255),
    telefono VARCHAR2(15),
    email VARCHAR2(100),
    estado VARCHAR2(20),
    fecha_registro DATE DEFAULT SYSDATE
);

CREATE TABLE Voluntario (
    voluntario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR2(15) UNIQUE NOT NULL,
    nombres VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    fecha_nacimiento DATE,
    email VARCHAR2(100),
    telefono VARCHAR2(15),
    direccion VARCHAR2(255),
    estado_civil VARCHAR2(30),
    fecha_registro DATE DEFAULT SYSDATE
);

CREATE TABLE Categoria (
    categoria_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    calificacion_max NUMBER(3)
);

CREATE TABLE Actividad (
    actividad_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id NUMBER NOT NULL,
    categoria_id NUMBER NOT NULL,
    nombre VARCHAR2(150) NOT NULL,
    descripcion VARCHAR2(255),
    ubicacion VARCHAR2(255),
    fecha_inicio DATE,
    fecha_fin DATE,
    estado VARCHAR2(20),
    CONSTRAINT fk_actividad_org FOREIGN KEY (organizacion_id) REFERENCES Organizacion (organizacion_id),
    CONSTRAINT fk_actividad_cat FOREIGN KEY (categoria_id) REFERENCES Categoria (categoria_id)
);

CREATE TABLE Donacion (
    donacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voluntario_id NUMBER NOT NULL,
    organizacion_id NUMBER NOT NULL,
    tipo_donacion_id NUMBER NOT NULL,
    cantidad NUMBER(10,2),
    fecha DATE DEFAULT SYSDATE,
    calificacion NUMBER(3),
    CONSTRAINT fk_donacion_vol FOREIGN KEY (voluntario_id) REFERENCES Voluntario (voluntario_id),
    CONSTRAINT fk_donacion_org FOREIGN KEY (organizacion_id) REFERENCES Organizacion (organizacion_id),
    CONSTRAINT fk_donacion_tipo FOREIGN KEY (tipo_donacion_id) REFERENCES Tipo_donacion (tipo_donacion_id)
);

CREATE TABLE Asignacion_actividades (
    asignacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voluntario_id NUMBER NOT NULL,
    actividad_id NUMBER NOT NULL,
    fecha DATE DEFAULT SYSDATE,
    estado VARCHAR2(20),
    calificacion NUMBER(3),
    CONSTRAINT fk_asignacion_vol FOREIGN KEY (voluntario_id) REFERENCES Voluntario (voluntario_id),
    CONSTRAINT fk_asignacion_act FOREIGN KEY (actividad_id) REFERENCES Actividad (actividad_id)
);

-- =============================================================================
-- 4. VISTAS (Views Originales - Útiles para consultas rápidas)
-- =============================================================================

CREATE OR REPLACE VIEW Donaciones_Detalladas AS
SELECT
    d.donacion_id, d.fecha AS fecha_donacion, d.cantidad, d.calificacion AS calificacion_donacion,
    v.voluntario_id, v.nombres || ' ' || v.apellidos AS nombre_voluntario, v.dni, v.email AS email_voluntario,
    o.organizacion_id, o.nombre AS nombre_organizacion, o.email AS email_organizacion,
    td.tipo_donacion_id, td.nombre AS tipo_donacion, td.descripcion AS descripcion_tipo_donacion
FROM Donacion d
JOIN Voluntario v ON d.voluntario_id = v.voluntario_id
JOIN Organizacion o ON d.organizacion_id = o.organizacion_id
JOIN Tipo_donacion td ON d.tipo_donacion_id = td.tipo_donacion_id;



CREATE OR REPLACE VIEW Vista_Donaciones AS
SELECT 
    d.donacion_id AS ID, v.nombres || ' ' || v.apellidos AS nombre_voluntario,
    o.nombre AS nombre_organizacion, td.nombre AS tipo_donacion,
    d.cantidad, d.fecha, d.calificacion, d.voluntario_id, d.organizacion_id, d.tipo_donacion_id
FROM Donacion d
JOIN Voluntario v ON d.voluntario_id = v.voluntario_id
JOIN Organizacion o ON d.organizacion_id = o.organizacion_id
JOIN Tipo_donacion td ON d.tipo_donacion_id = td.tipo_donacion_id
ORDER BY d.fecha DESC;


CREATE OR REPLACE VIEW Vista_Actividades AS
SELECT 
    a.actividad_id AS ID, o.nombre AS nombre_organizacion, c.nombre AS nombre_categoria,
    a.nombre AS nombre_actividad, a.descripcion, a.ubicacion, a.fecha_inicio, a.fecha_fin, a.estado,
    a.organizacion_id, a.categoria_id
FROM Actividad a
JOIN Organizacion o ON a.organizacion_id = o.organizacion_id
JOIN Categoria c ON a.categoria_id = c.categoria_id
ORDER BY a.fecha_inicio DESC;



CREATE OR REPLACE VIEW Organizaciones_Activas AS
SELECT organizacion_id, nombre, direccion, telefono, email, fecha_registro
FROM Organizacion WHERE UPPER(estado) = 'ACTIVA';  -- Corregido a 'ACTIVA' para coincidir con el paquete



CREATE OR REPLACE VIEW Organizaciones_Inactivas AS
SELECT organizacion_id, nombre, direccion, telefono, email, fecha_registro
FROM Organizacion WHERE UPPER(estado) = 'INACTIVO';



CREATE OR REPLACE VIEW Vista_Asignaciones AS
SELECT 
    aa.asignacion_id AS ID, v.nombres || ' ' || v.apellidos AS nombre_voluntario,
    a.nombre AS nombre_actividad, aa.fecha, aa.estado, aa.calificacion,
    aa.voluntario_id, aa.actividad_id, c.calificacion_max
FROM Asignacion_actividades aa
JOIN Voluntario v ON aa.voluntario_id = v.voluntario_id
JOIN Actividad a ON aa.actividad_id = a.actividad_id
JOIN Categoria c ON a.categoria_id = c.categoria_id
ORDER BY aa.fecha DESC;


-- =============================================================================
-- 5. PAQUETES (Lógica de Negocio Refactorizada)
-- Reemplaza a todos los procedimientos sueltos antiguos
-- =============================================================================

-- 5.1. PAQUETE ADMIN CORE
CREATE OR REPLACE PACKAGE PKG_ADMIN_CORE AS
    PROCEDURE Registrar_Organizacion(p_nombre VARCHAR2, p_direccion VARCHAR2, p_telefono VARCHAR2, p_email VARCHAR2);
    PROCEDURE Modificar_Organizacion(p_id NUMBER, p_nombre VARCHAR2, p_direccion VARCHAR2, p_telefono VARCHAR2, p_email VARCHAR2);
    PROCEDURE Cambiar_Estado_Organizacion(p_id NUMBER, p_estado VARCHAR2);
    PROCEDURE Listar_Organizaciones(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Buscar_Organizacion_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR);
END PKG_ADMIN_CORE;
/
CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_CORE AS
    PROCEDURE Registrar_Organizacion(p_nombre VARCHAR2, p_direccion VARCHAR2, p_telefono VARCHAR2, p_email VARCHAR2) IS
    BEGIN
        INSERT INTO Organizacion (nombre, direccion, telefono, email, estado) VALUES (p_nombre, p_direccion, p_telefono, p_email, 'ACTIVA');
        COMMIT;
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK; RAISE_APPLICATION_ERROR(-20003, 'Email o Nombre duplicado.');
    END;
    PROCEDURE Modificar_Organizacion(p_id NUMBER, p_nombre VARCHAR2, p_direccion VARCHAR2, p_telefono VARCHAR2, p_email VARCHAR2) IS
    BEGIN
        UPDATE Organizacion SET nombre = p_nombre, direccion = p_direccion, telefono = p_telefono, email = p_email WHERE organizacion_id = p_id;
        COMMIT;
    END;
    PROCEDURE Cambiar_Estado_Organizacion(p_id NUMBER, p_estado VARCHAR2) IS
    BEGIN
        UPDATE Organizacion SET estado = p_estado WHERE organizacion_id = p_id;
        COMMIT;
    END;
    PROCEDURE Listar_Organizaciones(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM Organizacion ORDER BY nombre;
    END;
    PROCEDURE Buscar_Organizacion_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM Organizacion WHERE organizacion_id = p_id;
    END;
END PKG_ADMIN_CORE;
/

-- 5.2. PAQUETE VOLUNTARIADO
    -- 5.2. PAQUETE VOLUNTARIADO (ESPECIFICACIÓN)
CREATE OR REPLACE PACKAGE PKG_VOLUNTARIADO AS
    -- Hacemos pública esta función para que el Trigger la pueda usar:
    FUNCTION Calcular_Estado_Actividad(p_f_inicio DATE, p_f_fin DATE) RETURN VARCHAR2;

    PROCEDURE Registrar_Voluntario(p_dni VARCHAR2, p_nombres VARCHAR2, p_apellidos VARCHAR2, p_fecha_nac DATE, p_email VARCHAR2, p_telefono VARCHAR2, p_direccion VARCHAR2, p_estado_civil VARCHAR2);
    PROCEDURE Modificar_Voluntario(p_id NUMBER, p_dni VARCHAR2, p_nombres VARCHAR2, p_apellidos VARCHAR2, p_fecha_nac DATE, p_email VARCHAR2, p_telefono VARCHAR2, p_direccion VARCHAR2, p_estado_civil VARCHAR2);
    PROCEDURE Listar_Voluntarios(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Buscar_Voluntario_Por_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Buscar_Voluntario_Por_DNI(p_dni IN VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Buscar_Voluntarios_Filtro(p_texto IN VARCHAR2, p_cursor OUT SYS_REFCURSOR);

    PROCEDURE Registrar_Actividad(p_org_id NUMBER, p_cat_id NUMBER, p_nombre VARCHAR2, p_desc VARCHAR2, p_ubicacion VARCHAR2, p_f_inicio DATE, p_f_fin DATE);
    PROCEDURE Modificar_Actividad(p_id NUMBER, p_org_id NUMBER, p_cat_id NUMBER, p_nombre VARCHAR2, p_desc VARCHAR2, p_ubicacion VARCHAR2, p_f_inicio DATE, p_f_fin DATE);
    PROCEDURE Listar_Actividades(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Buscar_Actividad_Por_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Buscar_Actividades_Filtro(p_texto IN VARCHAR2, p_cursor OUT SYS_REFCURSOR);

    PROCEDURE Asignar_Voluntario(p_vol_id NUMBER, p_act_id NUMBER, p_calif NUMBER DEFAULT NULL);
    PROCEDURE Modificar_Asignacion(p_id NUMBER, p_vol_id NUMBER, p_act_id NUMBER, p_estado VARCHAR2, p_calif NUMBER);
    PROCEDURE Listar_Asignaciones(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Buscar_Asignacion_Por_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR);
END PKG_VOLUNTARIADO;
/
    
CREATE OR REPLACE PACKAGE BODY PKG_VOLUNTARIADO AS
    FUNCTION Calcular_Estado_Actividad(p_f_inicio DATE, p_f_fin DATE) RETURN VARCHAR2 IS
    BEGIN
        IF p_f_inicio > SYSDATE THEN 
            RETURN 'Programada';
        ELSIF p_f_inicio <= SYSDATE AND (p_f_fin IS NULL OR p_f_fin > SYSDATE) THEN 
            RETURN 'En curso';
        ELSE 
            RETURN 'Finalizada';
        END IF;
    END Calcular_Estado_Actividad;

    -- ========================================================
    -- SECCIÓN VOLUNTARIOS
    -- ========================================================
    PROCEDURE Registrar_Voluntario(p_dni VARCHAR2, p_nombres VARCHAR2, p_apellidos VARCHAR2, p_fecha_nac DATE, p_email VARCHAR2, p_telefono VARCHAR2, p_direccion VARCHAR2, p_estado_civil VARCHAR2) IS
    BEGIN
        INSERT INTO Voluntario (dni, nombres, apellidos, fecha_nacimiento, email, telefono, direccion, estado_civil)
        VALUES (p_dni, p_nombres, p_apellidos, p_fecha_nac, p_email, p_telefono, p_direccion, p_estado_civil);
        COMMIT;
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK; RAISE_APPLICATION_ERROR(-20010, 'DNI o Email duplicado.');
    END Registrar_Voluntario;

    PROCEDURE Modificar_Voluntario(p_id NUMBER, p_dni VARCHAR2, p_nombres VARCHAR2, p_apellidos VARCHAR2, p_fecha_nac DATE, p_email VARCHAR2, p_telefono VARCHAR2, p_direccion VARCHAR2, p_estado_civil VARCHAR2) IS
    BEGIN
        UPDATE Voluntario SET dni=p_dni, nombres=p_nombres, apellidos=p_apellidos, fecha_nacimiento=p_fecha_nac, email=p_email, telefono=p_telefono, direccion=p_direccion, estado_civil=p_estado_civil
        WHERE voluntario_id = p_id;
        COMMIT;
    END Modificar_Voluntario;

    PROCEDURE Listar_Voluntarios(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM Voluntario ORDER BY apellidos;
    END Listar_Voluntarios;

    PROCEDURE Buscar_Voluntario_Por_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM Voluntario WHERE voluntario_id = p_id;
    END Buscar_Voluntario_Por_ID;

    PROCEDURE Buscar_Voluntario_Por_DNI(p_dni IN VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM Voluntario WHERE dni = p_dni;
    END Buscar_Voluntario_Por_DNI;

    PROCEDURE Buscar_Voluntarios_Filtro(p_texto IN VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM Voluntario 
        WHERE UPPER(dni) LIKE UPPER('%'||p_texto||'%') OR UPPER(apellidos) LIKE UPPER('%'||p_texto||'%')
        ORDER BY fecha_registro DESC;
    END Buscar_Voluntarios_Filtro;

    -- ========================================================
    -- SECCIÓN ACTIVIDADES
    -- ========================================================
    
    PROCEDURE Registrar_Actividad(p_org_id NUMBER, p_cat_id NUMBER, p_nombre VARCHAR2, p_desc VARCHAR2, p_ubicacion VARCHAR2, p_f_inicio DATE, p_f_fin DATE) IS
        v_estado VARCHAR2(20);
    BEGIN
        v_estado := Calcular_Estado_Actividad(p_f_inicio, p_f_fin);
        INSERT INTO Actividad (organizacion_id, categoria_id, nombre, descripcion, ubicacion, fecha_inicio, fecha_fin, estado)
        VALUES (p_org_id, p_cat_id, p_nombre, p_desc, p_ubicacion, p_f_inicio, p_f_fin, v_estado);
        COMMIT;
    END Registrar_Actividad;

    PROCEDURE Modificar_Actividad(p_id NUMBER, p_org_id NUMBER, p_cat_id NUMBER, p_nombre VARCHAR2, p_desc VARCHAR2, p_ubicacion VARCHAR2, p_f_inicio DATE, p_f_fin DATE) IS
        v_estado VARCHAR2(20);
    BEGIN
        v_estado := Calcular_Estado_Actividad(p_f_inicio, p_f_fin);
        UPDATE Actividad SET 
            organizacion_id = p_org_id, categoria_id = p_cat_id, nombre = p_nombre, 
            descripcion = p_desc, ubicacion = p_ubicacion, fecha_inicio = p_f_inicio, 
            fecha_fin = p_f_fin, estado = v_estado
        WHERE actividad_id = p_id;
        COMMIT;
    END Modificar_Actividad;

    PROCEDURE Listar_Actividades(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR 
            SELECT a.actividad_id, a.nombre, a.descripcion, a.ubicacion, a.fecha_inicio, a.fecha_fin, a.estado,
                   a.organizacion_id, o.nombre AS nombre_organizacion,
                   a.categoria_id, c.nombre AS nombre_categoria
            FROM Actividad a
            JOIN Organizacion o ON a.organizacion_id = o.organizacion_id
            JOIN Categoria c ON a.categoria_id = c.categoria_id
            ORDER BY a.fecha_inicio DESC;
    END Listar_Actividades;

    PROCEDURE Buscar_Actividad_Por_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR 
            SELECT a.actividad_id, a.nombre, a.descripcion, a.ubicacion, a.fecha_inicio, a.fecha_fin, a.estado,
                   a.organizacion_id, o.nombre AS nombre_organizacion,
                   a.categoria_id, c.nombre AS nombre_categoria
            FROM Actividad a
            JOIN Organizacion o ON a.organizacion_id = o.organizacion_id
            JOIN Categoria c ON a.categoria_id = c.categoria_id
            WHERE a.actividad_id = p_id;
    END Buscar_Actividad_Por_ID;

    PROCEDURE Buscar_Actividades_Filtro(p_texto IN VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR 
            SELECT a.actividad_id, a.nombre, a.descripcion, a.ubicacion, a.fecha_inicio, a.fecha_fin, a.estado,
                   a.organizacion_id, o.nombre AS nombre_organizacion,
                   a.categoria_id, c.nombre AS nombre_categoria
            FROM Actividad a
            JOIN Organizacion o ON a.organizacion_id = o.organizacion_id
            JOIN Categoria c ON a.categoria_id = c.categoria_id
            WHERE UPPER(a.nombre) LIKE UPPER('%'||p_texto||'%')
               OR UPPER(o.nombre) LIKE UPPER('%'||p_texto||'%')
            ORDER BY a.fecha_inicio DESC;
    END Buscar_Actividades_Filtro;

    -- ========================================================
    -- SECCIÓN ASIGNACIONES
    -- ========================================================
    PROCEDURE Asignar_Voluntario(p_vol_id NUMBER, p_act_id NUMBER, p_calif NUMBER DEFAULT NULL) IS
        v_existe NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_existe FROM Asignacion_actividades WHERE voluntario_id = p_vol_id AND actividad_id = p_act_id;
        IF v_existe > 0 THEN RAISE_APPLICATION_ERROR(-20062, 'El voluntario ya está inscrito en esa actividad.'); END IF;

        INSERT INTO Asignacion_actividades (voluntario_id, actividad_id, estado, calificacion, fecha)
        VALUES (p_vol_id, p_act_id, 'Pendiente', p_calif, SYSDATE);
        COMMIT;
    END Asignar_Voluntario;

    PROCEDURE Modificar_Asignacion(p_id NUMBER, p_vol_id NUMBER, p_act_id NUMBER, p_estado VARCHAR2, p_calif NUMBER) IS
    BEGIN
        UPDATE Asignacion_actividades SET 
            voluntario_id = p_vol_id, actividad_id = p_act_id, estado = p_estado, calificacion = p_calif
        WHERE asignacion_id = p_id;
        COMMIT;
    END Modificar_Asignacion;

    PROCEDURE Listar_Asignaciones(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR 
            SELECT aa.asignacion_id, aa.fecha, aa.estado, aa.calificacion,
                   aa.voluntario_id, v.nombres || ' ' || v.apellidos AS nombre_voluntario,
                   aa.actividad_id, a.nombre AS nombre_actividad
            FROM Asignacion_actividades aa
            JOIN Voluntario v ON aa.voluntario_id = v.voluntario_id
            JOIN Actividad a ON aa.actividad_id = a.actividad_id
            ORDER BY aa.fecha DESC;
    END Listar_Asignaciones;

    PROCEDURE Buscar_Asignacion_Por_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR 
            SELECT aa.asignacion_id, aa.fecha, aa.estado, aa.calificacion,
                   aa.voluntario_id, v.nombres || ' ' || v.apellidos AS nombre_voluntario,
                   aa.actividad_id, a.nombre AS nombre_actividad
            FROM Asignacion_actividades aa
            JOIN Voluntario v ON aa.voluntario_id = v.voluntario_id
            JOIN Actividad a ON aa.actividad_id = a.actividad_id
            WHERE aa.asignacion_id = p_id;
    END Buscar_Asignacion_Por_ID;

END PKG_VOLUNTARIADO;
/



-- 5.3. PAQUETE DONACIONES
CREATE OR REPLACE PACKAGE PKG_DONACIONES AS
    PROCEDURE Registrar_Donacion(p_vol_id NUMBER, p_org_id NUMBER, p_tipo_id NUMBER, p_cantidad NUMBER, p_calif NUMBER DEFAULT NULL);
    PROCEDURE Modificar_Donacion(p_don_id NUMBER, p_vol_id NUMBER, p_org_id NUMBER, p_tipo_id NUMBER, p_cantidad NUMBER, p_calif NUMBER DEFAULT NULL);
    PROCEDURE Listar_Todas(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Buscar_Por_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Buscar_Filtro(p_texto IN VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Listar_Donaciones_Voluntario(p_vol_id NUMBER, p_cursor OUT SYS_REFCURSOR);
END PKG_DONACIONES;
/
CREATE OR REPLACE PACKAGE BODY PKG_DONACIONES AS
    PROCEDURE Registrar_Donacion(p_vol_id NUMBER, p_org_id NUMBER, p_tipo_id NUMBER, p_cantidad NUMBER, p_calif NUMBER DEFAULT NULL) IS
    BEGIN
        FOR r IN (SELECT estado FROM Organizacion WHERE organizacion_id = p_org_id) LOOP
            IF r.estado != 'ACTIVA' THEN RAISE_APPLICATION_ERROR(-20051, 'Organización Inactiva'); END IF;
        END LOOP;
        INSERT INTO Donacion (voluntario_id, organizacion_id, tipo_donacion_id, cantidad, calificacion)
        VALUES (p_vol_id, p_org_id, p_tipo_id, p_cantidad, p_calif);
        COMMIT;
    END;
    PROCEDURE Modificar_Donacion(p_don_id NUMBER, p_vol_id NUMBER, p_org_id NUMBER, p_tipo_id NUMBER, p_cantidad NUMBER, p_calif NUMBER DEFAULT NULL) IS
    BEGIN
        FOR r IN (SELECT estado FROM Organizacion WHERE organizacion_id = p_org_id) LOOP
            IF r.estado != 'ACTIVA' THEN RAISE_APPLICATION_ERROR(-20051, 'Organización Inactiva'); END IF;
        END LOOP;
        UPDATE Donacion SET voluntario_id = p_vol_id, organizacion_id = p_org_id, tipo_donacion_id = p_tipo_id, cantidad = p_cantidad, calificacion = p_calif WHERE donacion_id = p_don_id;
        COMMIT;
    END;
    PROCEDURE Listar_Todas(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT d.donacion_id, d.cantidad, d.fecha, d.calificacion, d.voluntario_id, v.nombres || ' ' || v.apellidos AS nombre_voluntario, d.organizacion_id, o.nombre AS nombre_organizacion, d.tipo_donacion_id, td.nombre AS nombre_tipo FROM Donacion d JOIN Voluntario v ON d.voluntario_id = v.voluntario_id JOIN Organizacion o ON d.organizacion_id = o.organizacion_id JOIN Tipo_donacion td ON d.tipo_donacion_id = td.tipo_donacion_id ORDER BY d.fecha DESC;
    END;
    PROCEDURE Buscar_Por_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT d.donacion_id, d.cantidad, d.fecha, d.calificacion, d.voluntario_id, v.nombres || ' ' || v.apellidos AS nombre_voluntario, d.organizacion_id, o.nombre AS nombre_organizacion, d.tipo_donacion_id, td.nombre AS nombre_tipo FROM Donacion d JOIN Voluntario v ON d.voluntario_id = v.voluntario_id JOIN Organizacion o ON d.organizacion_id = o.organizacion_id JOIN Tipo_donacion td ON d.tipo_donacion_id = td.tipo_donacion_id WHERE d.donacion_id = p_id;
    END;
    PROCEDURE Buscar_Filtro(p_texto IN VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT d.donacion_id, d.cantidad, d.fecha, d.calificacion, d.voluntario_id, v.nombres || ' ' || v.apellidos AS nombre_voluntario, d.organizacion_id, o.nombre AS nombre_organizacion, d.tipo_donacion_id, td.nombre AS nombre_tipo FROM Donacion d JOIN Voluntario v ON d.voluntario_id = v.voluntario_id JOIN Organizacion o ON d.organizacion_id = o.organizacion_id JOIN Tipo_donacion td ON d.tipo_donacion_id = td.tipo_donacion_id WHERE UPPER(v.nombres) LIKE UPPER('%'||p_texto||'%') OR UPPER(v.apellidos) LIKE UPPER('%'||p_texto||'%') OR UPPER(o.nombre) LIKE UPPER('%'||p_texto||'%') ORDER BY d.fecha DESC;
    END;
    PROCEDURE Listar_Donaciones_Voluntario(p_vol_id NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM Donacion WHERE voluntario_id = p_vol_id; 
    END;
END PKG_DONACIONES;
/


-- 5.4. PAQUETE REPORTES
CREATE OR REPLACE PACKAGE PKG_REPORTES AS
    PROCEDURE Obtener_Dashboard_Impacto(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Obtener_Top_Donantes(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE Reporte_Actividades(p_cursor OUT SYS_REFCURSOR);
END PKG_REPORTES;
/
CREATE OR REPLACE PACKAGE BODY PKG_REPORTES AS
    PROCEDURE Obtener_Dashboard_Impacto(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT o.nombre AS Organizacion, COUNT(d.donacion_id) AS Total_Transacciones, NVL(SUM(d.cantidad), 0) AS Total_Recaudado, AVG(NVL(d.calificacion, 0)) AS Satisfaccion_Promedio FROM Organizacion o LEFT JOIN Donacion d ON o.organizacion_id = d.organizacion_id WHERE o.estado = 'ACTIVA' GROUP BY o.nombre ORDER BY Total_Recaudado DESC;
    END;
    PROCEDURE Obtener_Top_Donantes(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT v.nombres || ' ' || v.apellidos AS Voluntario, COUNT(d.donacion_id) AS Nro_Donaciones, SUM(d.cantidad) AS Total_Donado FROM Voluntario v JOIN Donacion d ON v.voluntario_id = d.voluntario_id GROUP BY v.voluntario_id, v.nombres, v.apellidos ORDER BY Total_Donado DESC FETCH FIRST 5 ROWS ONLY;
    END;
    PROCEDURE Reporte_Actividades(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT a.nombre AS Actividad, c.nombre AS Categoria, o.nombre AS Organizadora, a.estado, TO_CHAR(a.fecha_inicio, 'DD/MM/YYYY') AS Fecha_Inicio FROM Actividad a JOIN Categoria c ON a.categoria_id = c.categoria_id JOIN Organizacion o ON a.organizacion_id = o.organizacion_id ORDER BY a.fecha_inicio DESC;
    END;
END PKG_REPORTES;
/

-- =============================================================================
-- 6. TRIGGERS
-- =============================================================================

CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_ESTADO_ACT
BEFORE INSERT OR UPDATE OF fecha_inicio, fecha_fin ON Actividad
FOR EACH ROW
BEGIN
    -- Usa lógica centralizada del paquete
    :NEW.estado := PKG_VOLUNTARIADO.Calcular_Estado_Actividad(:NEW.fecha_inicio, :NEW.fecha_fin);
END;
/

-- =============================================================================
-- 7. DATOS DE PRUEBA (SEED DATA)
-- =============================================================================
SET SERVEROUTPUT ON;
DECLARE
    v_org_id NUMBER;
    v_vol_id NUMBER;
    v_cat_id NUMBER;
    v_tipo_id NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- INICIANDO CARGA DE DATOS ---');

    -- Maestros
    INSERT INTO Tipo_donacion (nombre, descripcion, calificacion_max) VALUES ('Efectivo', 'Donación monetaria', 10);
    INSERT INTO Categoria (nombre, descripcion, calificacion_max) VALUES ('Ayuda Social', 'Eventos comunitarios', 10);
    COMMIT;
    
    SELECT MAX(tipo_donacion_id) INTO v_tipo_id FROM Tipo_donacion;
    SELECT MAX(categoria_id) INTO v_cat_id FROM Categoria;

    -- Organización
    PKG_ADMIN_CORE.Registrar_Organizacion('Fundación Futuro', 'Av. Larco 123', '999888777', 'contacto@futuro.org');
    SELECT MAX(organizacion_id) INTO v_org_id FROM Organizacion;

    -- Voluntario
    PKG_VOLUNTARIADO.Registrar_Voluntario('87654321', 'Juan', 'Perez', TO_DATE('1990-01-01','YYYY-MM-DD'), 'juan@mail.com', '999000111', 'Lima', 'Soltero');
    SELECT MAX(voluntario_id) INTO v_vol_id FROM Voluntario;

    -- Actividad
    PKG_VOLUNTARIADO.Registrar_Actividad(v_org_id, v_cat_id, 'Navidad para Todos', 'Entrega de regalos', 'Plaza de Armas', SYSDATE+5, SYSDATE+6);

    -- Donación
    PKG_DONACIONES.Registrar_Donacion(v_vol_id, v_org_id, v_tipo_id, 500.00, 10);

    DBMS_OUTPUT.PUT_LINE('--- CARGA DE DATOS COMPLETADA ---');
END;

/
SET SERVEROUTPUT ON;
DECLARE
    v_vol_id NUMBER;
    v_act_id NUMBER;
BEGIN
    -- Obtenemos los IDs existentes
    SELECT MAX(voluntario_id) INTO v_vol_id FROM Voluntario;
    SELECT MAX(actividad_id) INTO v_act_id FROM Actividad;

    -- Llamamos al paquete para crear la asignación
    PKG_VOLUNTARIADO.Asignar_Voluntario(
        p_vol_id => v_vol_id,
        p_act_id => v_act_id,
        p_calif  => NULL -- Aún no tiene calificación
    );

    DBMS_OUTPUT.PUT_LINE('¡Voluntario asignado exitosamente!');
    COMMIT;
END;
/
